Natural number arithmetic
HoTT/Coq-HoTT pull request #1653
Opened 2022-05-23 08:49 UTC by patrick-nicodemus

We add some theorems of natural number arithmetic involving pred, S,  + , -, < and <=.
We define a hint database for natural number arithmetic and add some lemmas to it.
We define a "left-handed" <= as an inductive type in the other obvious way, namely:
n <= n
n + 1 <= m  ->  n <= m
and prove it's equivalent to the other one.
This is useful for cases where you want to loop from 0 to m, going from bottom to top; if you induct on the normal definition of <= then you will loop from top to bottom.

We prove "strong induction" for N, i.e,   if P is a predicate on N and P is inductive (forall n, (forall m < n , P m) -> P m) then P holds for all n.

We show that if P is a decidable predicate on N and there is some k such that P k, there is a least natural number k such that P k.

2022-05-30 04:09 UTC, mikeshulman requested changes
This looks pretty good to me.  Aside from the points I mentioned specifically, I think a better name for the file would be something like `Spaces/Nat/Arithmetic`.

2022-05-30 04:09 UTC, mikeshulman commented on theories/Spaces/natural_number_arithmetic.v
> +Class ComplementaryProp (A B : Type) :=
This is a general definition not specific to natural numbers, so I would put it in a separate file.  Perhaps `Basics/Decidable`?

2022-05-30 04:09 UTC, mikeshulman commented on theories/Spaces/natural_number_arithmetic.v
> +Fixpoint leq_bool (n m : nat) : Bool :=
This and some other definitions in this file have names that don't make sense globally, as they don't specify that they involve `nat`.

2022-05-30 04:09 UTC, mikeshulman commented on theories/Spaces/natural_number_arithmetic.v
> +Proposition natminuspluseq : forall n m : nat, n <= m -> (m - n) + n = m.
Generally we use underscores to separate words in the names of definitions and theorems.

2022-06-09 02:57 UTC, mikeshulman commented on theories/Basics/Decidable.v
> +Class ComplementaryProp (A B : Type) :=
Maybe put it at the end of the file?  In this place, it breaks the referent "this" in the preceding comment, which is supposted to refer to the definition of `Decidable` below.

2022-10-05 05:23 UTC, mikeshulman commented
Did you force-push the right thing?  Now it looks like the *only* change in this PR is adding `ComplementaryProp`.

2022-10-08 23:12 UTC, jdchristensen reviewed
I'm not really able to review the overall approach here.  My comments are mainly minor stylistic issues.  (Also, this appears to be WIP.  Maybe mark it as "draft" until it is ready for full review?)

2022-10-08 23:12 UTC, jdchristensen commented on theories/Basics/BooleanReflection.v
> +  Proposition refl_tofalse (A : Type) (b : Bool) (p : reflect A b) : ~ A -> b = false.
Is "refl" short for "reflect"?  "refl" is used for the reflexivity path in the HoTT book, so I think it would be better to use "reflect" here.

2022-10-08 23:12 UTC, jdchristensen commented on theories/Basics/BooleanReflection.v
> +  Proposition refl_totrue (A : Type) (b : Bool) (p : reflect A b) : A -> b = true.
Maybe be consistent about using A, B, ... vs P, Q, ...?

2022-10-08 23:12 UTC, jdchristensen commented on theories/Basics/BooleanReflection.v
> +  Qed.
We usually use "Defined" unless there is a good reason not to.

2022-10-08 23:12 UTC, jdchristensen commented on theories/Classes/implementations/assume_rationals.v
> +  (Qrats : Rationals@{UQ UQ UQ UQ UQ UQ UQ UQ UQ UQ} Q)
I'm surprised that *additional* universe variables are required.  Any idea how that happened?

2022-10-08 23:12 UTC, jdchristensen commented on theories/Classes/interfaces/abstract_algebra.v
> +    := field_characteristic : forall n : nat, Nat.lt 0 n ->
Can the universe variable `i` be completely eliminated here?  (If not, it should be listed alongside the `j` in `FieldCharacteristic@{j}`.)

2022-10-08 23:12 UTC, jdchristensen commented on theories/Spaces/Nat.v
> +Print lt.
Remove.

2022-10-08 23:12 UTC, jdchristensen commented on theories/Spaces/Nat/Arithmetic.v
> +  Definition Sleq_rect :
`:` at start of next line, after two spaces.

2022-10-08 23:12 UTC, jdchristensen commented on theories/Spaces/Nat/Arithmetic.v
> +         - apply succ, IHl0, leq_implies_Sleq; assumption.
Incorrect indentation.

2022-10-08 23:12 UTC, jdchristensen commented on theories/Spaces/Nat/Arithmetic.v
> +(* Proposition iff_reflect (P : Type) (b : Bool) : (reflect P b) <-> (P <-> b = true). *)
Lots of commented out stuff?

2022-10-08 23:12 UTC, jdchristensen commented on theories/Spaces/Nat/Arithmetic.v
> +Qed.
`Defined`, here and elsewhere?

2022-10-09 15:28 UTC, jdchristensen commented on theories/Classes/implementations/assume_rationals.v
> +  (Qrats : Rationals@{UQ UQ UQ UQ UQ UQ UQ UQ UQ UQ} Q)
(This comment and the one about `FieldCharacteristic` might be related.  It's possible that by removing the universe variable from `lt`, some universe variables become "freer", which means that in subsequent definitions, they aren't forced to be equal.  And then those subsequent definitions end up with *more* universe parameters.  So it would be worth checking whether some universe variables (like the `i` in `FieldCharacteristic`) can be eliminated.  Semantically, it's not clear why the rationals need any universe variables at all...)

2022-10-09 15:39 UTC, SkySkimmer commented on theories/Classes/interfaces/abstract_algebra.v
> +    := field_characteristic : forall n : nat, Nat.lt 0 n ->
i is the universe of A from the section, section universes are not listed in the @{}

2022-10-09 15:41 UTC, SkySkimmer commented on theories/Basics/SProp.v
> +Record Box (A : SProp) : Type0 := box { unbox : A }.
Unset Primitive Projections around this record to remove the warning

2022-10-09 19:26 UTC, patrick-nicodemus commented on theories/Basics/BooleanReflection.v
> +  Proposition refl_tofalse (A : Type) (b : Bool) (p : reflect A b) : ~ A -> b = false.
Ok, this is a good point.

2022-10-09 19:28 UTC, patrick-nicodemus commented on theories/Classes/implementations/assume_rationals.v
> +  (Qrats : Rationals@{UQ UQ UQ UQ UQ UQ UQ UQ UQ UQ} Q)
This is not clear to me either. My guess is that since this is an interface, the idea is that the underlying structures which implement it could potentially be arbitrarily complex as long as they expose the desired functionality to the user?

2022-10-09 21:51 UTC, patrick-nicodemus commented on theories/Basics/BooleanReflection.v
> +  Proposition refl_totrue (A : Type) (b : Bool) (p : reflect A b) : A -> b = true.
Yep, agreed.

2022-10-09 21:54 UTC, patrick-nicodemus commented
> I'm not really able to review the overall approach here. My comments are mainly minor stylistic issues. (Also, this appears to be WIP. Maybe mark it as "draft" until it is ready for full review?)

Ok, marked as draft for the time being. I would appreciate you continuing to make comments and suggestions anyway, please let me know when you think it is appropriate for it to be ready for full review. I would rather have small parts integrated if they are useful than try to submit a big monolithic chunk of code and discuss it for a long time.

2022-10-09 21:54 UTC, patrick-nicodemus commented on theories/Basics/SProp.v
> +Record Box (A : SProp) : Type0 := box { unbox : A }.
Thank you, done.

2022-10-09 22:09 UTC, SkySkimmer commented on theories/Spaces/Nat/Arithmetic.v
> +Require Import HoTT.SProp.
There is no Coq.Init.Sprop, only Coq.Logic.StrictProp

2022-10-09 22:12 UTC, mikeshulman commented
> I would rather have small parts integrated if they are useful than try to submit a big monolithic chunk of code and discuss it for a long time.

That's a good idea and would make it easier to review.  But in that case, you should separate out the small parts into separate pull requests.  For instance, it would probably be appropriate to have separate PRs for the boolean stuff and for the sprop stuff.

2022-10-09 22:34 UTC, patrick-nicodemus commented on theories/Spaces/Nat/Arithmetic.v
> +Qed.
Thanks, all theorems in this file have been changed to Defined.
The style guide makes the following statements:

> If the value of something being defined matters, then you must either give an explicit term defining it, or construct it with tactics and end the proof with Defined. But if all that matters is that you have defined something with a given type, you can construct it with tactics and end the proof with Qed. The latter makes the term "opaque" so that it doesn't "compute".
> 
>  If something can be made opaque, it is generally preferable to do so, for performance reasons. However, many things which a traditional type theorist would make opaque cannot be opaque in homotopy type theory. For instance, none of the higher-groupoid structure in PathGroupoids can be made opaque, not even the "coherence laws". If you doubt this, try making some of it opaque and you will find that the "higher coherences" such as pentagon and eckmann_hilton will fail to typecheck.

You said earlier that "We usually use "Defined" unless there is a good reason not to." I think it would be helpful to clarify this point in the style guide. For example,
> The important thing is that when defining a transparent term with tactics, you should restrict yourself to tactics which maintain a high degree of control over the resulting term; ... Even plain rewrite is usually to be avoided in this context: although the terms it produces are at least predictable, they are one big transport (under a different name) whereas a term we would want to reason about ought to be constructed using smaller pieces like ap and concat which we can understand.

Since the proof uses rewrites, I terminated the proof with Qed. 
I discussed this issue the other day with @mikeshulman in the Zulip and he said that the proof terms that arise from running destruct on an equality are less complex than those arising from rewrite, so here I was able to replace all "rewrites" with "destructs" and there is no conflict.

2022-10-09 22:43 UTC, patrick-nicodemus commented on theories/Basics/BooleanReflection.v
> +  Proposition refl_tofalse (A : Type) (b : Bool) (p : reflect A b) : ~ A -> b = false.
I have removed those theorems in the new commit. I am thinking I will use the theorem names in here.
https://coq.inria.fr/distrib/V8.16.0/stdlib/Coq.ssr.ssrbool.html

2022-10-09 23:15 UTC, patrick-nicodemus commented on theories/Spaces/Nat/Arithmetic.v
> +Require Import HoTT.SProp.
Ok, thank you. I don't know what the error is. "Require SProp" and "Require Import SProp" give errors which I don't understand.

2022-10-09 23:25 UTC, Alizter commented
Regarding the proof terms of rewrite. Now that we have 8.16 we could start using the generalized rewriting feature of Coq (formly setoid_rewrite). If we spent some time setting this up we could have nice proof terms when doing rewrites. It would be similar to an attempt at nice rewrite terms by @jdchristensen from a few years ago.

2022-10-10 00:57 UTC, patrick-nicodemus commented
@mikeshulman Ok, I got overly excited. SProp and BooleanReflection stuff deleted from the commit so we can just talk about natural number arithmetic stuff, I will open a second PR request soon for the boolean reflection stuff, SProp stuff seems like it might need further discussion.

2022-10-10 02:40 UTC, mikeshulman commented on theories/Spaces/Nat/Arithmetic.v
> +Qed.
I would actually be inclined to make these `Qed`s as you originally had them.  Firstly, because of the rewrites, the resulting proof terms are not going to be very nice to look at; and secondly, they inhabit hprops (equalities in nat), so at least propositionally their definitional value doesn't matter.  It seems unlikely to me that we would ever need these to be transparent.

2022-10-10 02:42 UTC, mikeshulman commented on theories/Spaces/Nat/Arithmetic.v
> +Qed.
In particular, aAs you quoted from the style guide, I think that elsewhere we do often use `Qed` for proofs involving `rewrite`.  I think there are some places where we found some value in making rewrite proofs transparent, but I thought in general we were sticking to Qed for rewrite proofs.

2022-10-10 08:40 UTC, SkySkimmer commented on theories/Spaces/Nat/Arithmetic.v
> +Require Import HoTT.SProp.
Probably because SProp is a keyword ie treated specially by the parser

2022-10-10 08:42 UTC, SkySkimmer commented
Is setoid_rewrite considered to have nice proof terms?

2022-10-10 08:55 UTC, Alizter commented
@SkySkimmer Since we can give the rewrite instances directly, we can fill it with concatenations and aps depending on the form of the term.

2022-10-10 13:53 UTC, jdchristensen commented on theories/Classes/implementations/assume_rationals.v
> +  (Qrats : Rationals@{UQ UQ UQ UQ UQ UQ UQ UQ UQ UQ} Q)
Right, since it's an interface, it should accommodate implementations that don't live in `Type0`.  But I'm still confused why additional universe variables appeared.  The attached screenshot shows how the universe variables changed in `Rationals`.  The new variables are u7 and u8, and in the old version they were always replaced by u6.  Odd.  Not a big deal, but I'm just curious, as I hoped that changing `lt` would *reduce* universe variables elsewhere.

![Screenshot from 2022-10-10 09-49-48](https://user-images.githubusercontent.com/3374048/194881969-517f22d1-c15a-4909-badd-a8f1b2e5bbce.png)

2022-10-10 13:53 UTC, jdchristensen commented on theories/Classes/interfaces/abstract_algebra.v
> +    := field_characteristic : forall n : nat, Nat.lt 0 n ->
Ah, sorry, I missed that `i` was defined earlier and is an important universe variable that can't be eliminated.

2022-10-10 14:02 UTC, SkySkimmer commented on theories/Classes/implementations/assume_rationals.v
> +  (Qrats : Rationals@{UQ UQ UQ UQ UQ UQ UQ UQ UQ UQ} Q)
What does the change in RationalsToField look like?

2022-10-26 00:57 UTC, patrick-nicodemus commented on theories/Classes/interfaces/abstract_algebra.v
> +    := field_characteristic : forall n : nat, Nat.lt 0 n ->
Is this resolved?

2022-10-26 13:26 UTC, jdchristensen commented on theories/Classes/implementations/assume_rationals.v
> +  (Qrats : Rationals@{UQ UQ UQ UQ UQ UQ UQ UQ UQ UQ} Q)
(Even though we didn't get to the bottom of why extra universe variables appear here, I don't think this should hold up this PR.)

2022-11-13 18:48 UTC, patrick-nicodemus commented
@mikeshulman Your original "changes requested" applied to an early draft of this PR before I threw out a bunch of independent things like stuff related to boolean reflection or SPRop. Can you take another look at it and update the changes requested?

2022-11-22 14:46 UTC, closed without merging